<a href="https://colab.research.google.com/github/SalwaMustafa/DEPI-Task-1/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [ ]:
import numpy as np
arr1D = np.arange(0,10)
print(arr1D)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2D_1 = np.zeros((3,3))
print(arr2D_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr2D_2 = np.ones((2,4))
print(arr2D_2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr2D_3 = np.eye(3)
print(arr2D_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

2

In [ ]:
arr.size

6


## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr[:,2]

array([30, 60, 90])

In [ ]:
print(arr[1,2])

60


In [ ]:
arr[:, ::-1]

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])


---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

In [ ]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
arr[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[:,[2,3]]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [ ]:
arr[[1,2]][:,[1,2]]

array([[ 6,  7],
       [10, 11]])


---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
arr1 + arr2

array([5, 7, 9])

In [ ]:
arr1 * arr2

array([ 4, 10, 18])

In [ ]:
arr1**2

array([1, 4, 9])

In [ ]:
arr2**2

array([16, 25, 36])


## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])

In [ ]:
A + B

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
A * B

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [ ]:
B - 10

array([ 0, 10, 20])

In [ ]:
A + C

array([[2, 3, 4],
       [6, 7, 8]])


---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

In [ ]:
A + B

array([[100, 201, 302, 403],
       [104, 205, 306, 407],
       [108, 209, 310, 411]])

In [ ]:
C * B

array([[ 200,  400,  600,  800],
       [ 300,  600,  900, 1200],
       [ 400,  800, 1200, 1600]])

In [ ]:
A + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])


---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
myarr = arr.reshape(3,4)
myarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
myarr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [ ]:
np.vstack((A, B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((A, B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
C = np.arange(16).reshape(4, 4)
C.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])


## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [ ]:
arr = np.array([[5, 10, 15], [20, 25, 30]])

In [ ]:
arr[arr > 10]

array([15, 20, 25, 30])

In [ ]:
arr[arr % 2 == 0] = -1
arr

array([[ 5, -1, 15],
       [-1, 25, -1]])


---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(np.sum(arr))

21


In [ ]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
np.max(arr, axis=1)

array([3, 6])

In [ ]:
print(np.std(arr))

1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])


---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [ ]:
np.random.rand(2,3)

array([[0.65509427, 0.84905174, 0.90841257],
       [0.65301211, 0.58586478, 0.30424414]])

In [ ]:
np.random.randint(50,101,10)

array([ 79,  89,  61,  70,  69,  87,  71, 100,  79,  81])


---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [ ]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

In [ ]:
print(np.linalg.matrix_rank(A))

3


In [ ]:
np.linalg.inv(A)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [ ]:
print(np.linalg.det(A))

0.9999999999999964



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [ ]:
arr = np.arange(36).reshape(6, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
submatrices = []
for i in range(4):
  for j in range(4):
    submatrices.append(arr[i:i+3 , j:j+3])

submatrices

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]]),
 array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 8,  9, 10],
        [14, 15, 16],
        [20, 21, 22]]),
 array([[ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]),
 array([[12, 13, 14],
        [18, 19, 20],
        [24, 25, 26]]),
 array([[13, 14, 15],
        [19, 20, 21],
        [25, 26, 27]]),
 array([[14, 15, 16],
        [20, 21, 22],
        [26, 27, 28]]),
 array([[15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]]),
 array([[18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[19, 20, 21],
        [25, 26, 27],
        [31, 32, 33]]),
 array([[20, 21, 22],
        [26, 27, 28],
    


---

Happy coding! 🎯
